### ISSUE TITLE
License

### ISSUE THREAD

**Issue by maltesl** [omegahm/ku-frontpage#11]
My understanding of the GPLv3 is that if I use this package in a tex document and distribute the compiled pdf, then I will have to make my source code available under the GPLv3 as well. Is this intended? If not, would it be possible to license the package under a license that does not place restrictions on only using it with `\usepackage` e.g. the LPPL 1.3c (or perhaps the LGPLv3)?

I personally use the GPL in some personal projects as well, so this should not be taken as arguing against the GPL, but the manner in which ku-frontpage is distributed by KU on https://designguide.ku.dk/skabeloner/word/specialer/ makes me suspect that at least they might not be aware of this consequence. I also have the strong impression that fellow ph.d. students using ku-frontpage are generally unaware of it.

**Comment by omegahm** [comment]
Hi @maltesl. Thanks for opening this issue. 

As I am no longer affiliated with University of Copenhagen, I might not be the correct person to house the `ku-frontpage` LaTeX package anymore.

---

I'm no expert in licenses and there seems to be a lot of different opinions (https://opensource.stackexchange.com/questions/2735/gpl-licensed-latex-template-implications-for-resulting-work) on how GPL works in LaTeX files.

Do you know what the options are for changing the license? I don't believe I can just change the `LICENSE` file and call it a day, can I? 😅

**Comment by maltesl** [comment]
I have actually also written to someone at KU about this among other things (they offer version 0.1 of ku-frontpage for download). If you change the license to something non-viral (so that it doesn't impact my thesis itself) and for which this is possible then I might also fork it and make some updates to it, if that is ok. (For example since last year we are not supposed to use the faculty logos anymore, but everyone is supposed to use the red KU logo, perhaps this is why KU only offers version 0.1.)

I am not a lawyer, and this is not legal advice:

If all copyright holders agree (and according to the file you are the only copyright holder) then I think you can publish ku-frontpage.sty under a new license by just pushing a version in which you edit the third line of ku-frontpage.sty to say
`% Distributed under the terms of [new license]` and change `LICENSE` to the text of the new license. Or if you use a short license (like the MIT license) you could also put it directly in `ku-frontpage.sty` and remove `LICENSE`.

People will still be able to use the versions up to now under the conditions of the GPLv3, but can alternatively use the new version under the new license.

I see that for some of your other repos you use the MIT license, perhaps that would be a good choice? In my first post above I mentioned the LPPL, as that seems to be often used for LaTeX packages, but it has a kind-of-weird clause 6 that makes forking a bit cumbersome.

**Comment by omegahm** [comment]
I have merged https://github.com/omegahm/ku-frontpage/pull/12 which moves this project to the MIT License.

**Comment by maltesl** [comment]
Perfect, thanks!
