### ISSUE TITLE
(Optionally) leave the margins alone

### ISSUE THREAD

**Issue by athas** [omegahm/ku-frontpage#3]
I'm happy that someone fixed up the ku-forside mess so I don't have to do it myself all the time.  I even added a reference to [ucph.dk](http://ucph.dk/)!

However, I don't think ku-frontpage should (permanently) modify the margins of the document.  While I can disable it by commenting out the following line, I would prefer a less invasive approach.
```
\RequirePackage[a4paper, hmargin={55pt, 55pt}, vmargin={2.8cm, 2.8cm}]{geometry}
```
I do not mind tiny margins on the front page, but they look horrible for the main text.  I think ku-frontpage should be a package solely for getting a KU-themed front-page (as the name suggests), and leave the job of crippling LaTeX with Word-isms to another package.

**Comment by omegahm** [comment]
I agree, and I had already made the changes locally, I just hadn't pushed it here yet. 🙈
